language: cpp
sudo: required
dist: xenial
compiler:
- gcc
os:
- linux
addons:
  apt:
    packages:
      - sshpass
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git libboost-all-dev libtbb-dev cmake libfftw3-3 libfftw3-dev
script:
    - wget https://root.cern/download/root_v6.12.06.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
    - tar xzf root_v6.12.06.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
    - source root/bin/thisroot.sh

    - rm -rf j-pet-framework || true
    - git clone --single-branch --branch cmake https://github.com/grey277/j-pet-framework.git
    - mkdir -p j-pet-framework/build
    - cd j-pet-framework/build
    - cmake ..
    - cmake --build .
    - sudo make install
    - cd ../..

    - mkdir build
    - cd build
    - cmake ..
    - make
    - make tests_largebarrel
    - make tests_imagereconstruction
    
    - cd ImageReconstruction
    - ctest -j6 -C Debug -T test --output-on-failure
    - cd ..

    - cd LargeBarrelAnalysis
    - ctest -j6 -C Debug -T test --output-on-failure
    - wget http://sphinx.if.uj.edu.pl/~alek/framework_integration_tests/dabc_17025151847.hld
    - wget http://sphinx.if.uj.edu.pl/~alek/framework_integration_tests/setupRun3.json
    - ./LargeBarrelAnalysis.x -t hld -f dabc_17025151847.hld -l setupRun3.json -i 3 -r 0 100
    - mkdir outdir
    - ./LargeBarrelAnalysis.x -t hld -f dabc_17025151847.hld -l setupRun3.json -i 3 -r 0 100 -o outdir
    - ./LargeBarrelAnalysis.x -t root -f dabc_17025151847.hld.root -l setupRun3.json -i 3 -r 0 100
    - sed -i 's/manager.useTask("TimeWindowCreator", "hld", "tslot.calib");//' ../../LargeBarrelAnalysis/main.cpp
    - make LargeBarrelAnalysis.x
    - ./LargeBarrelAnalysis.x -t root -f dabc_17025151847.tslot.calib.root   -r 0 100
